import express from 'express';
import Hello from './Hello.js';
import Lab5 from "./Lab5.js";
import cors from "cors";
import UserRoutes from './Users/routes.js';
import CourseRoutes from "./Kanbas/courses/routes.js";
import ModuleRoutes from "./Kanbas/modules/routes.js";
import mongoose from 'mongoose';
const app = express();
app.use(cors());
app.use(express.json());
mongoose.connect("mongodb://localhost:27017/kanbas");
ModuleRoutes(app);
CourseRoutes(app);
Lab5(app);
Hello(app);
UserRoutes(app);
app.listen(process.env.PORT || 4000);